export default {
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
    CHANGE_IS_BANED: 'CHANGE_IS_BANED',
    CHANGE_IS_BANED_SUCCESS: 'CHANGE_IS_BANED_SUCCESS',
    CHANGE_IS_BANED_ERROR: 'CHANGE_IS_BANED_ERROR',
    GET_ALL_USERS_UPDATE: 'GET_ALL_USERS_UPDATE',
};