export default {
    MAIL_SERVICE: "MAIL_SERVICE",
    GET_MAIL_SERVICE_RESULT: "GET_MAIL_SERVICE_RESULT",
    CREATE_LINK_FOR_MAIL: "CREATE_LINK_FOR_MAIL",
    RESET_API_MSG: "RESET_API_MSG",
    RESET_APP_MSG: "RESET_APP_MSG",
    MODAL_STATE: "MODAL_STATE",
    NEW_MESSAGE: "NEW_MESSAGE",
    SITE_NAVIGATION: "SITE_NAVIGATION",
    CHANGE_APP_STATE: "CHANGE_APP_STATE",
    DASHBOARD: 'DASHBOARD',
    DASHBOARD_CHANGED: 'DASHBOARD_CHANGED',
};