export default {
    CHANGE_FILTER_TAGS: "CHANGE_FILTER_TAGS",
    CHANGE_CONTEST_FILTER: "CHANGE_CONTEST_FILTER",
    SET_FILTERED_CONTEST: "SET_FILTERED_CONTEST",
    GET_CONTESTS_BY_STARTER_FILTER: "GET_CONTESTS_BY_STARTER_FILTER",
    SEND_FILTER_DATA: "SEND_FILTER_DATA",
    FILTERED_CONTEST_REQUEST: "FILTERED_CONTEST_REQUEST",
    CONTESTS_BY_ID_REQUEST: "CONTESTS_BY_ID_REQUEST",
    CONTESTS_BY_ID_RESPONSE: "CONTESTS_BY_ID_RESPONSE",
};